// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Lrd6lxVkiCgGzE92W-6q6Hi0CS9v3qo',
    appId: '1:506369953090:web:5441f31c935f3bbdc98cdb',
    messagingSenderId: '506369953090',
    projectId: 'fleeting-monitoring-app',
    authDomain: 'fleeting-monitoring-app.firebaseapp.com',
    storageBucket: 'fleeting-monitoring-app.firebasestorage.app',
    measurementId: 'G-1NQCMFRQT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDuIvsjgdGiAc-orYi53_6xUTnTw5ZM9w',
    appId: '1:506369953090:android:fb8c043db2a9caa0c98cdb',
    messagingSenderId: '506369953090',
    projectId: 'fleeting-monitoring-app',
    storageBucket: 'fleeting-monitoring-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByPiKca7n3GPCWKH9miM2KPvGH_ZHap3w',
    appId: '1:506369953090:ios:005428bca5fa3e81c98cdb',
    messagingSenderId: '506369953090',
    projectId: 'fleeting-monitoring-app',
    storageBucket: 'fleeting-monitoring-app.firebasestorage.app',
    iosBundleId: 'com.example.fleetingMonitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByPiKca7n3GPCWKH9miM2KPvGH_ZHap3w',
    appId: '1:506369953090:ios:005428bca5fa3e81c98cdb',
    messagingSenderId: '506369953090',
    projectId: 'fleeting-monitoring-app',
    storageBucket: 'fleeting-monitoring-app.firebasestorage.app',
    iosBundleId: 'com.example.fleetingMonitoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Lrd6lxVkiCgGzE92W-6q6Hi0CS9v3qo',
    appId: '1:506369953090:web:22784afb919958dfc98cdb',
    messagingSenderId: '506369953090',
    projectId: 'fleeting-monitoring-app',
    authDomain: 'fleeting-monitoring-app.firebaseapp.com',
    storageBucket: 'fleeting-monitoring-app.firebasestorage.app',
    measurementId: 'G-PCGKNK6B0W',
  );
}
